include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    omit_local_variable_types: false
    public_member_api_docs: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    avoid_redundant_argument_values: false
    non_constant_identifier_names: false
    overridden_fields: false
    require_trailing_commas: false
