name: directus_api
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  directus: ^0.7.0
  equatable: ^2.0.0
  fresh_graphql: ^0.5.1
  graphql: ^5.0.1-beta.3
  http: ^0.13.1
  json_annotation: ^4.4.0

dev_dependencies:
  artemis: ^7.2.2-beta
  build_runner: ^2.0.1
  coverage: ^1.0.2
  json_serializable: ^6.1.4
  meta: ^1.3.0
  mocktail: ^0.1.1
  test: ^1.17.1
  very_good_analysis: ^2.0.3
